#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int PROPORTIONAL_GAIN =40;
//const int INTEGRALGAIN = 0;
const int DERIVATE_GAIN = 6;
//const int GOAL_POINT = 0;

void move(int speed){

	motor[motorB] = speed;
	motor[motorC] = speed;

}

void updateProportional(int *proportionalTerm){
		*proportionalTerm = PROPORTIONAL_GAIN * getGyroDegrees(gyroSensor);
}

void updateDerivate(int *derivateTerm){
		*derivateTerm = DERIVATE_GAIN * getGyroRate(gyroSensor);
}

int PIDSpeed(int *proportionalTerm, int *derivateTerm){
	return (*proportionalTerm + *derivateTerm)/8;
}

task main(){

	int speed = 0;
	int proportionalTerm = 0, derivateTerm = 0;

	resetGyro(gyroSensor);

	while(getGyroDegrees(gyroSensor) < 60 && getGyroDegrees(gyroSensor) > -60){

	updateProportional(&proportionalTerm);

	updateDerivate(&derivateTerm);

	speed = PIDSpeed(&proportionalTerm, &derivateTerm);

	move(speed);


	}


}
